api_controllers:
    type: attribute
    prefix: /api/v1/
    name_prefix: api.
    resource:
        path: ../src/Controller/Api/
        namespace: App\Controller\Api

controllers:
    type: attribute
    resource: ../src/Controller/HomeController.php

api_login_check:
    path: /api/login_check

api_refresh_token:
    path: /api/token/refresh
